### ISSUE TITLE
Request for example training data

### ISSUE THREAD

**Issue by sendwin** [RichardYang40148/MidiNet#11]
I'm trying to replicate midinet as described in your paper but I'm unclear on the format of the data required. Would it be possible to obtain an example dataset for data_X, prev_X and data_Y? Thanks in advance

**Comment by mbalazs98** [comment]
I have the same issue, is it supposed to be a midi file converted to png?

**Comment by RichardYang40148** [comment]
Hi, I recommend to look into the followup research of MidiNet: https://salu133445.github.io/lakh-pianoroll-dataset/ . This time, we use an open sourced dataset, and the code for data preprocessing is also available as a toolbox.
