### ISSUE TITLE
Generator final layer 

### ISSUE THREAD

**Issue by slyforce** [RichardYang40148/MidiNet#3]
In the Arxiv Preprint, https://arxiv.org/abs/1703.10847, you mention in Section 4.2 that you use a layer that zeros out all outputs except the one with the highest value. 

In this implementation, however, you simply apply a sigmoid layer to the output of the generator. Could you please explain why you chose the sigmoidal output?

**Comment by RichardYang40148** [comment]
Hi,
It's a procedure only during generation(choose the note with highest value for each time step), sorry I didn't clarify that in the paper.
