### ISSUE TITLE
train data shape

### ISSUE THREAD

**Issue by vicuvicuvicuna** [RichardYang40148/MidiNet#7]
Hello Richard,

I am trying to train my own npy dataset, but I couldn't find the exact shapes of your dataset in model.py.
Could you tell me the exact shapes of train dataset?

**Comment by RichardYang40148** [comment]
Hi, 
It's  (n, 1, 16, 128), where n is the number of measures for training data.
Thanks for bringing this up! I'll add this to the comments of model.py, line 134-136

**Comment by vicuvicuvicuna** [comment]
Thank you!!

**Comment by RichardYang40148** [comment]
https://github.com/RichardYang40148/MidiNet/blob/acfc779610a2ba926f4dcb6ce6ac2200c46a1169/v1/model.py#L134-L135
